---
# vars file for cudnn
cudnn_installer_map:
  xenial:
    v7.1:
      v9.2:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7_7.1.4.18-1+cuda9.2_amd64.deb
    v7.0:
      v9.1:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7_7.0.5.15-1+cuda9.1_amd64.deb
      v9.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb 
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7_7.0.5.15-1+cuda8.0_amd64.deb
    v7.1-dev:
      v9.2:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7-dev_7.1.4.18-1+cuda9.2_amd64.deb
    v7.0-dev:
      v9.1:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7-dev_7.0.5.15-1+cuda9.1_amd64.deb 
      v9.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7-dev_7.0.5.15-1+cuda9.0_amd64.deb
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7-dev_7.0.5.15-1+cuda8.0_amd64.deb
    v6.0:
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn6_6.0.21-1+cuda8.0_amd64.deb 
    v6.0-dev:
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn6-dev_6.0.21-1+cuda8.0_amd64.deb
  zesty:
    v7.1:
      v9.2:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7_7.1.4.18-1+cuda9.2_amd64.deb
    v7.0:
      v9.1:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7_7.0.5.15-1+cuda9.1_amd64.deb
      v9.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb 
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7_7.0.5.15-1+cuda8.0_amd64.deb
    v7.1-dev:
      v9.2:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7-dev_7.1.4.18-1+cuda9.2_amd64.deb
    v7.0-dev:
      v9.1:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7-dev_7.0.5.15-1+cuda9.1_amd64.deb 
      v9.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7-dev_7.0.5.15-1+cuda9.0_amd64.deb
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn7-dev_7.0.5.15-1+cuda8.0_amd64.deb
    v6.0:
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn6_6.0.21-1+cuda8.0_amd64.deb
    v6.0-dev:
      v8.0:
        deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/libcudnn6-dev_6.0.21-1+cuda8.0_amd64.deb

cudnn_runtime_installer: "{{ cudnn_installer_map[ansible_distribution_release][cudnn_run_version_str][cuda_version_str]}}"
cudnn_developer_installer: "{{ cudnn_installer_map[ansible_distribution_release][cudnn_dev_version_str][cuda_version_str]}}"