---
- name: Install CUDNN runtime library
  apt: "deb={{ cudnn_runtime_installer.deb }} state=present update_cache=yes"

- name: Install CUDNN developer library
  apt: "deb={{ cudnn_developer_installer.deb }} state=present update_cache=yes"
