---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install main packages
  apt: name={{item}} state=present
  with_items:
    - htop
    - tmux
    - vim
    - curl
    - wget
    - git
    - rsync
    - iotop
    - iftop
    - unzip
    - python3-pip
    - docker-py
